---
# this comment is a hack
version: '3'
services:
  homer:
    image: b4bz/homer:v23.10.1
    container_name: homer
    volumes:
      - /docker/stacks/homer/assets/:/www/assets
    ports:
      - 8080:8080
    environment:
     - UID=1000
     - GID=1000
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
