# configure Docker Swarm Cluster (DEV)
- name: configure Docker Swarm Cluster (DEV)
  hosts:
    - vespae_LB
  vars:
    - jenkins_path: "/var/lib/jenkins/workspace/Swarm_Lab_dev_test"
  tasks:

    - name: Ensure Nginx config folder exists
      ansible.builtin.file:
        path: /etc/nginx/swarm_sites
        state:  directory

    - name: install the custom nginx.conf
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/nginx.conf"
        dest: /etc/nginx/nginx.conf

    # - name: create swarm_sites folder with configs
    #   ansible.builtin.copy:
    #     src:  "{{ jenkins_path }}/nginx/DEV_swarm_sites/"
    #     dest: "/etc/nginx/swarm_sites/"

    - name: install the custom portainer LB config
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/DEV/portainer_LB.conf"
        dest: /etc/nginx/portainer_LB.conf

    - name: install the stack LB configs into sites-available
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/DEV/nginx_{{ item }}.conf"
        dest: "/etc/nginx/sites-available/nginx_{{ item }}.conf"
      loop:
        - "homer"

    - name: enable stacks from sites-available
      ansible.builtin.file:
        src:    "/etc/nginx/sites-available/nginx_{{ item }}.conf"
        dest:   "/etc/nginx/sites-enabled/nginx_{{ item }}.conf"
        state:  link
      loop:
        - "homer"

    - name: restart nginx & related services
      systemd:
        name:     "{{ item }}.service"
        state:    restarted
        enabled:  yes
      loop:
        - nginx

- name: Deploy the code and all required infrastructure
  hosts:
    - swarm_data
  tasks:

    # - name: create any required directories
    #   ansible.builtin.file:
    #     path:   "{{ item }}"
    #     state:  directory
    #   loop:
    #     - tbd

    - name: deploy the code
      ansible.builtin.git:
        repo:     "https://github.com/educatedCaveman/swarm_lab"
        dest:     /mnt/docker/DEV/
        version:  dev_test
        force:    true