# configure Docker Swarm Cluster (DEV)
- name: configure Docker Swarm Cluster (DEV)
  hosts:
    - vespae_LB
  vars:
    - jenkins_path: "/var/lib/jenkins/workspace/Swarm_Lab_dev_test"
    # - jenkins_path: "/var/lib/jenkins/workspace/Swarm_Lab_dev_test@tmp"
  tasks:

    - name: Ensure Nginx config folder exists
      ansible.builtin.file:
        path: /etc/nginx/swarm_sites
        state:  directory

    - name: copy swarm site configs
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/DEV/{{ item }}.conf"
        dest: "/etc/nginx/swarm_sites/{{ item }}.conf"
      loop:
        - homer

    - name: install the custom nginx.conf
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/nginx.conf"
        dest: /etc/nginx/nginx.conf

    - name: install the swarm sites config
      ansible.builtin.copy:
        src:  "{{ jenkins_path }}/nginx/vespae.conf"
        dest: /etc/nginx/swarm_sites.conf

    - name: restart nginx & related services
      systemd:
        name:     "{{ item }}.service"
        state:    restarted
        enabled:  yes
      loop:
        - nginx

- name: Deploy the code and all required infrastructure
  hosts:
    - swarm_data
  tasks:

    # - name: create any required directories
    #   ansible.builtin.file:
    #     path:   "{{ item }}"
    #     state:  directory
    #   loop:
    #     - tbd

    - name: deploy the code
      ansible.builtin.git:
        repo:     "https://github.com/educatedCaveman/swarm_lab"
        dest:     /mnt/docker/DEV/
        version:  dev_test
        force:    true